name: ASV Benchmarking

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  benchmark:
    name: Linux
    runs-on: ubuntu-latest
    env:
      ASV_DIR: "./benchmarks"
      CONDA_ENV_FILE: ci/environment.yml

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ${{env.CONDA_ENV_FILE}}
          cache-environment: true
          environment-name: uxarray_build
          cache-environment-key: "${{runner.os}}-${{runner.arch}}-py${{env.PYTHON_VERSION}}-${{env.TODAY}}-${{hashFiles(env.CONDA_ENV_FILE)}}-benchmark"
          create-args: >-
            asv
            build
            mamba

      # - name: Checkout uxarray
      #   uses: actions/checkout@v4
      #   with:
      #     repository: UXARRAY/uxarray
      #     ref: main
      #     fetch-depth: 0

      # - name: Fetch all tags and branches for uxarray
      #   run: |
      #     git fetch --all --tags

      - name: Checkout uxarray-asv
        uses: actions/checkout@v4
        with:
          repository: UXARRAY/uxarray-asv
          persist-credentials: false
          fetch-depth: 0
          ref: main
          path: uxarray-asv

      - name: Copy existing results
        run: |
          if [ -d "uxarray-asv/results" ]; then
            cp -r uxarray-asv/results benchmarks/
          fi

      - name: Run benchmarks
        shell: bash -l {0}
        id: benchmark
        run: |
          cd benchmarks
          asv machine --machine GH-Actions --os ubuntu-latest --arch x64 --cpu "2-core unknown" --ram 7GB
          asv run v2024.02.0..main --skip-existing --parallel || true
        working-directory: ${{ env.ASV_DIR }}


      - name: Commit and push benchmark results
        run: |
          if [ -d "uxarray-asv/results" ]; then
            rm -r uxarray-asv/results
          fi
          cp -r benchmarks/results/ uxarray-asv/
          cd uxarray-asv
          git config --local user.email "${{ secrets.UXARRAY_ASV_EMAIL }}"
          git config --local user.name "${{ secrets.UXARRAY_ASV_USER_NAME }}"
          git add results
          git commit -m "[🤖] Update benchmark results"

      - name: Push to uxarray-asv
        if: github.ref == 'refs/heads/main' && github.repository == 'UXARRAY/uxarray'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.UXARRAY_ASV_PAT }}
          branch: main
          force: true
          repository: UXARRAY/uxarray-asv
          directory: uxarray-asv
