name: Benchmark PR 

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:

jobs:
  benchmark:
    if: ${{ contains( github.event.pull_request.labels.*.name, 'run-benchmark') && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Linux
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
    env:
      ASV_DIR: "./benchmarks"
      CONDA_ENV_FILE: ci/asv.yml

    steps:
      - name: Checkout uxarray
        uses: actions/checkout@v4
        with:
          repository: philipc2/uxarray
          ref: main
          fetch-depth: 0

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: "24.1.2-0"
          activate-environment: asv

      - name: Get date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache environment
        uses: actions/cache@v4
        with:
          path: ${{ env.CONDA }}/envs
          key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ hashFiles('./ci/asv.yml') }}-${{ env.CACHE_NUMBER }}
        env:
          CACHE_NUMBER: 0
        id: cache

      - name: Update environment
        run:
          conda env update -n asv -f ./ci/asv.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Conda list
        run: |
          conda info
          conda list

      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          repository: philipc2/uxarray
          ref: main
          path: main_repo
          fetch-depth: 0

      - name: Run Benchmarks Compared to Main
        shell: bash -l {0}
        id: benchmark
        run: |
          cd benchmarks
          echo "Baseline:  ${{ github.event.pull_request.base.sha }} (${{ github.event.pull_request.base.label }})"
          echo "Contender: ${GITHUB_SHA} (${{ github.event.pull_request.head.label }})"
          ASV_OPTIONS="--split --show-stderr --factor 1"
          asv continuous $ASV_OPTIONS ${{ github.event.pull_request.base.sha }} ${GITHUB_SHA} \
              | sed "/Traceback \|failed$\|PERFORMANCE DECREASED/ s/^/::error::/" \
              | tee benchmarks.log
          # Report and export results for subsequent steps
          if grep "Traceback \|failed\|PERFORMANCE DECREASED" benchmarks.log > /dev/null ; then
              exit 1
          fi
